apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: yao
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: yao
  template:
    metadata:
      labels:
        app: yao
{{/*      annotations: TODO: fix with argo diff */}}
{{/*        rollme: {{ randAlphaNum 5 | quote }}*/}}
    spec:
      containers:
        - name: yao
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "150m"
              memory: "150Mi"
            limits:
              cpu: "500m"
              memory: "500Mi"
          envFrom:
          - secretRef:
              name: yao-secret
      imagePullSecrets:
      - name: yao-read-registry
