apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: yao
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  selector:
    matchLabels:
      app: yao
  template:
    metadata:
      labels:
        app: yao
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: yao
          image: ghcr.io/theophanevie/yao:master
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
          envFrom:
          - secretRef:
              name: {{ .Release.Name }}-secret
      imagePullSecrets:
      - name: {{ .Release.Name }}-read-registry
